//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WingkouWeb.ImageProcessingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessMethod", Namespace="http://schemas.datacontract.org/2004/07/ImageProcessingService")]
    [System.SerializableAttribute()]
    public partial class ProcessMethod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageProcessingService.IImageProcessingService")]
    public interface IImageProcessingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageProcessingService/ProcessImage", ReplyAction="http://tempuri.org/IImageProcessingService/ProcessImageResponse")]
        string ProcessImage(string uri, string methodName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageProcessingService/ProcessImage", ReplyAction="http://tempuri.org/IImageProcessingService/ProcessImageResponse")]
        System.Threading.Tasks.Task<string> ProcessImageAsync(string uri, string methodName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageProcessingService/GetAvailableMethod", ReplyAction="http://tempuri.org/IImageProcessingService/GetAvailableMethodResponse")]
        WingkouWeb.ImageProcessingService.ProcessMethod[] GetAvailableMethod();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageProcessingService/GetAvailableMethod", ReplyAction="http://tempuri.org/IImageProcessingService/GetAvailableMethodResponse")]
        System.Threading.Tasks.Task<WingkouWeb.ImageProcessingService.ProcessMethod[]> GetAvailableMethodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageProcessingService/GetLastError", ReplyAction="http://tempuri.org/IImageProcessingService/GetLastErrorResponse")]
        System.Exception GetLastError();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImageProcessingService/GetLastError", ReplyAction="http://tempuri.org/IImageProcessingService/GetLastErrorResponse")]
        System.Threading.Tasks.Task<System.Exception> GetLastErrorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImageProcessingServiceChannel : WingkouWeb.ImageProcessingService.IImageProcessingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageProcessingServiceClient : System.ServiceModel.ClientBase<WingkouWeb.ImageProcessingService.IImageProcessingService>, WingkouWeb.ImageProcessingService.IImageProcessingService {
        
        public ImageProcessingServiceClient() {
        }
        
        public ImageProcessingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageProcessingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageProcessingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageProcessingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ProcessImage(string uri, string methodName) {
            return base.Channel.ProcessImage(uri, methodName);
        }
        
        public System.Threading.Tasks.Task<string> ProcessImageAsync(string uri, string methodName) {
            return base.Channel.ProcessImageAsync(uri, methodName);
        }
        
        public WingkouWeb.ImageProcessingService.ProcessMethod[] GetAvailableMethod() {
            return base.Channel.GetAvailableMethod();
        }
        
        public System.Threading.Tasks.Task<WingkouWeb.ImageProcessingService.ProcessMethod[]> GetAvailableMethodAsync() {
            return base.Channel.GetAvailableMethodAsync();
        }
        
        public System.Exception GetLastError() {
            return base.Channel.GetLastError();
        }
        
        public System.Threading.Tasks.Task<System.Exception> GetLastErrorAsync() {
            return base.Channel.GetLastErrorAsync();
        }
    }
}
